//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:36:58 PM CET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for engineClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="engineClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Electric"/>
 *     &lt;enumeration value="Glow"/>
 *     &lt;enumeration value="Special"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "engineClass")
@XmlEnum
public enum EngineClass {

    @XmlEnumValue("Electric")
    ELECTRIC("Electric"),
    @XmlEnumValue("Glow")
    GLOW("Glow"),
    @XmlEnumValue("Special")
    SPECIAL("Special");
    private final String value;

    EngineClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EngineClass fromValue(String v) {
        for (EngineClass c: EngineClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
